# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityInSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.PositiveSmallIntegerField(choices=[(0, 'Grid'), (1, 'Stack')], default=0)),
                ('starts_new_row', models.BooleanField(default=True, help_text='If True, the viewer will force new line before this entity.')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Entity')),
            ],
            options={
                'verbose_name_plural': 'Entities in Section',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='According to the Entity type, this will be the field label or the column header.', max_length=50)),
                ('field_type', models.CharField(choices=[('char_value', 'String'), ('integer_value', 'Integer'), ('boolean_value', 'Boolean')], default='char_value', max_length=50)),
                ('help_text', models.TextField(blank=True, help_text='Will be displayed on site.', null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('parent_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Field')),
                ('select_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Field', verbose_name='select from list')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Will be displayed on site.', max_length=50)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('related_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Will be displayed on site.', max_length=50)),
                ('help_text', models.TextField(blank=True, help_text='Will be displayed on site.', null=True)),
                ('entities', models.ManyToManyField(through='ccenter.EntityInSection', to='ccenter.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='SectionInPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True)),
                ('display_value', models.CharField(blank=True, help_text='Used for list item display', max_length=200, null=True)),
                ('char_value', models.CharField(blank=True, max_length=200, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('boolean_value', models.BooleanField()),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Field')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(through='ccenter.SectionInPage', to='ccenter.Section'),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(to='ccenter.Tag'),
        ),
        migrations.AddField(
            model_name='entityinsection',
            name='fields',
            field=models.ManyToManyField(to='ccenter.Field'),
        ),
        migrations.AddField(
            model_name='entityinsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Section'),
        ),
        migrations.AddField(
            model_name='entity',
            name='fields',
            field=models.ManyToManyField(to='ccenter.Field'),
        ),
        migrations.AddField(
            model_name='entity',
            name='parent_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Entity'),
        ),
    ]
