# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('header', models.CharField(help_text='Will be displayed on site.', max_length=50)),
                ('help_text', models.TextField(blank=True, help_text='Will be displayed on site.', null=True)),
                ('description', models.TextField(blank=True, help_text='Internal. Will not be displayed on site.', null=True)),
                ('entity_type', models.IntegerField(choices=[(0, 'Single Value'), (1, 'List'), (2, 'Grid')], default=0, verbose_name='type')),
                ('single_value_options', models.IntegerField(choices=[(0, 'Default'), (1, 'Drop down'), (2, 'Radio Buttons')], default=0, verbose_name='show as')),
                ('list_value_options', models.IntegerField(choices=[(0, 'Default'), (1, 'Check boxes')], default=0, verbose_name='show as')),
                ('list_grid_allow_add', models.BooleanField(default=True, verbose_name='allow add')),
                ('list_grid_allow_delete', models.BooleanField(default=True, verbose_name='allow delete')),
                ('list_grid_min', models.IntegerField(default=0, verbose_name='minimum items')),
                ('list_grid_max', models.IntegerField(blank=True, default=None, help_text='Leave blank for no limit.', null=True, verbose_name='maximum items')),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='EntityInSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_new_row', models.BooleanField(default=True, help_text='If false, the viewer will force new line before this entity.')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Entity')),
            ],
            options={
                'verbose_name_plural': 'Entities in Section',
            },
        ),
        migrations.CreateModel(
            name='EntityValueDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='According to the Entity type, this will be the field label or the column header.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='For grid.')),
                ('attribute', models.CharField(blank=True, help_text='To identify the value by the consumers', max_length=50, null=True)),
                ('value_type', models.CharField(choices=[('char_value', 'String'), ('integer_value', 'Integer'), ('boolean_value', 'Boolean')], default='char_value', max_length=50)),
                ('help_text', models.TextField(blank=True, help_text='Will be displayed on site.', null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Entity')),
                ('select_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.EntityValueDefinition', verbose_name='select from list')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_add', models.BooleanField(default=True)),
                ('allow_delete', models.BooleanField(default=True)),
                ('list_type', models.PositiveSmallIntegerField(choices=[(0, 'Listbox'), (1, 'Dropdown'), (2, 'Radio buttons'), (2, 'Checkboxes')], default=1)),
                ('multi_select', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='GridRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('header', models.CharField(help_text='Will be displayed on site.', max_length=50)),
                ('help_text', models.TextField(blank=True, help_text='Will be displayed on site.', null=True)),
                ('description', models.TextField(blank=True, help_text='Internal. Will not be displayed on site.', null=True)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('folder', models.ManyToManyField(to='ccenter.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('header', models.CharField(help_text='Will be displayed on site.', max_length=50)),
                ('help_text', models.TextField(blank=True, help_text='Will be displayed on site.', null=True)),
                ('description', models.TextField(blank=True, help_text='Internal. Will not be displayed on site.', null=True)),
                ('entities', models.ManyToManyField(through='ccenter.EntityInSection', to='ccenter.Entity')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionInPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('display_value', models.CharField(blank=True, help_text='Used for list item display', max_length=200, null=True)),
                ('char_value', models.CharField(blank=True, max_length=200, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('boolean_value', models.BooleanField()),
                ('value_field', models.CharField(blank=True, max_length=20, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('grid_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.GridRow')),
                ('value_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.EntityValueDefinition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(through='ccenter.SectionInPage', to='ccenter.Section'),
        ),
        migrations.AddField(
            model_name='extendedproperties',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.Section'),
        ),
        migrations.AddField(
            model_name='entityinsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Section'),
        ),
    ]
