# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvaluedefinition',
            name='value_type',
            field=models.CharField(choices=[('char_value', 'String'), ('integer_value', 'Integer'), ('boolean_value', 'Boolean')], default='char_value', max_length=50),
        ),
    ]
