# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccenter', '0002_auto_20170309_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
