# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccenter', '0003_auto_20170504_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedproperties',
            name='list_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Listbox'), (1, 'Dropdown'), (2, 'Radio buttons'), (2, 'Checkboxes')], default=1),
        ),
        migrations.AddField(
            model_name='extendedproperties',
            name='multi_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='value',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
