# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccenter', '0004_auto_add_list_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='display_value',
            field=models.CharField(blank=True, help_text='Used for list item display', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
