# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccenter', '0006_auto_20170508_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityvaluedefinition',
            name='help_text',
            field=models.TextField(blank=True, help_text='Will be displayed on site.', null=True),
        ),
    ]
