# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccenter', '0008_entityvaluedefinition_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccenter.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='value',
            name='grid_row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccenter.GridRow'),
        ),
    ]
